name: Seurity workflow

on: [ push ]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    name: Scan Git repo
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-scan-repo-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-scan-repo-results.sarif'

      # - name: Upload Trivy scan results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: trivy-scan-repo-results.sarif
      #     path: '${{ github.workspace }}/trivy-scan-repo-results.sarif'

      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          scan-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: dependency-results.sbom.json
          path: '${{ github.workspace }}/dependency-results.sbom.json'